CREATE DATABASE api_db;
USE api_db;

CREATE TABLE api_keys (
id INT AUTO_INCREMENT PRIMARY KEY,
api_key_hash VARCHAR(255) NOT NULL,
user_id INT DEFAULT NULL,
is_active BOOLEAN DEFAULT TRUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UNIQUE (api_key_hash)
);


CREATE TABLE events (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
date DATETIME NOT NULL,
location VARCHAR(255) DEFAULT NULL,
description TEXT DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL DEFAULT NULL
);